# Generated by Django 4.0.1 on 2022-02-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0002_customer_remove_booking_rooms_booking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='checkouts',
            field=models.ManyToManyField(blank=True, related_name='guests', to='Lodge.Checkout'),
        ),
    ]
