# Generated by Django 4.0.1 on 2022-02-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0003_checkout_customer_checkouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='checkin_date',
            new_name='checkout_date',
        ),
    ]
