# Generated by Django 4.0.1 on 2022-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0004_rename_checkin_date_checkout_checkout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='checkouts',
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('email', models.CharField(blank=True, max_length=240, null=True)),
                ('checkouts', models.ManyToManyField(blank=True, related_name='guests', to='Lodge.Checkout')),
            ],
        ),
    ]
