# Generated by Django 4.0.1 on 2022-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lodge', '0005_remove_customer_checkouts_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='checkouts',
            field=models.ManyToManyField(blank=True, related_name='guests', to='Lodge.Checkout'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
